# Description: Consolidated country data for the Telegram bot.
# This file serves as the single source of truth for country codes, names,
# currencies, and standard Unicode emoji flags.

# Source: Primarily from app.py, merged with data from other scripts.

SUPPORTED_COUNTRIES = {
    "AE": {"name": "阿联酋", "currency": "AED", "symbol": "د.إ"},
    "AG": {"name": "安提瓜和巴布达", "currency": "XCD", "symbol": "$"},
    "AI": {"name": "安圭拉", "currency": "XCD", "symbol": "$"},
    "AL": {"name": "阿尔巴尼亚", "currency": "ALL", "symbol": "L"},
    "AM": {"name": "亚美尼亚", "currency": "AMD", "symbol": "֏"},
    "AO": {"name": "安哥拉", "currency": "AOA", "symbol": "Kz"},
    "AR": {"name": "阿根廷", "currency": "ARS", "symbol": "$"},
    "AT": {"name": "奥地利", "currency": "EUR", "symbol": "€"},
    "AU": {"name": "澳大利亚", "currency": "AUD", "symbol": "A$"},
    "AZ": {"name": "阿塞拜疆", "currency": "AZN", "symbol": "₼"},
    "BB": {"name": "巴巴多斯", "currency": "BBD", "symbol": "$"},
    "BE": {"name": "比利时", "currency": "EUR", "symbol": "€"},
    "BF": {"name": "布基纳法索", "currency": "XOF", "symbol": "CFA"},
    "BG": {"name": "保加利亚", "currency": "BGN", "symbol": "лв"},
    "BH": {"name": "巴林", "currency": "BHD", "symbol": ".د.ب"},
    "BJ": {"name": "贝宁", "currency": "XOF", "symbol": "CFA"},
    "BM": {"name": "百慕大", "currency": "BMD", "symbol": "$"},
    "BN": {"name": "文莱", "currency": "BND", "symbol": "$"},
    "BO": {"name": "玻利维亚", "currency": "BOB", "symbol": "Bs."},
    "BR": {"name": "巴西", "currency": "BRL", "symbol": "R$"},
    "BS": {"name": "巴哈马", "currency": "BSD", "symbol": "$"},
    "BW": {"name": "博茨瓦纳", "currency": "BWP", "symbol": "P"},
    "BY": {"name": "白俄罗斯", "currency": "BYN", "symbol": "Br"},
    "BZ": {"name": "伯利兹", "currency": "BZD", "symbol": "BZ$"},
    "CA": {"name": "加拿大", "currency": "CAD", "symbol": "C$"},
    "CH": {"name": "瑞士", "currency": "CHF", "symbol": "CHF"},
    "CL": {"name": "智利", "currency": "CLP", "symbol": "$"},
    "CN": {"name": "中国", "currency": "CNY", "symbol": "¥"},
    "CO": {"name": "哥伦比亚", "currency": "COP", "symbol": "$"},
    "CR": {"name": "哥斯达黎加", "currency": "CRC", "symbol": "₡"},
    "CV": {"name": "佛得角", "currency": "CVE", "symbol": "$"},
    "CY": {"name": "塞浦路斯", "currency": "EUR", "symbol": "€"},
    "CZ": {"name": "捷克", "currency": "CZK", "symbol": "Kč"},
    "DE": {"name": "德国", "currency": "EUR", "symbol": "€"},
    "DK": {"name": "丹麦", "currency": "DKK", "symbol": "kr"},
    "DM": {"name": "多米尼克", "currency": "XCD", "symbol": "$"},
    "DO": {"name": "多米尼加共和国", "currency": "DOP", "symbol": "RD$"},
    "DZ": {"name": "阿尔及利亚", "currency": "DZD", "symbol": "دج"},
    "EC": {"name": "厄瓜多尔", "currency": "USD", "symbol": "$"},
    "EE": {"name": "爱沙尼亚", "currency": "EUR", "symbol": "€"},
    "EG": {"name": "埃及", "currency": "EGP", "symbol": "£"},
    "ES": {"name": "西班牙", "currency": "EUR", "symbol": "€"},
    "FI": {"name": "芬兰", "currency": "EUR", "symbol": "€"},
    "FJ": {"name": "斐济", "currency": "FJD", "symbol": "$"},
    "FM": {"name": "密克罗尼西亚", "currency": "USD", "symbol": "$"},
    "FR": {"name": "法国", "currency": "EUR", "symbol": "€"},
    "GB": {"name": "英国", "currency": "GBP", "symbol": "£"},
    "GD": {"name": "格林纳达", "currency": "XCD", "symbol": "$"},
    "GH": {"name": "加纳", "currency": "GHS", "symbol": "₵"},
    "GM": {"name": "冈比亚", "currency": "GMD", "symbol": "D"},
    "GR": {"name": "希腊", "currency": "EUR", "symbol": "€"},
    "GT": {"name": "危地马拉", "currency": "GTQ", "symbol": "Q"},
    "GW": {"name": "几内亚比绍", "currency": "XOF", "symbol": "CFA"},
    "GY": {"name": "圭亚那", "currency": "GYD", "symbol": "$"},
    "HK": {"name": "香港", "currency": "HKD", "symbol": "HK$"},
    "HN": {"name": "洪都拉斯", "currency": "HNL", "symbol": "L"},
    "HR": {"name": "克罗地亚", "currency": "HRK", "symbol": "kn"},
    "HU": {"name": "匈牙利", "currency": "HUF", "symbol": "Ft"},
    "ID": {"name": "印度尼西亚", "currency": "IDR", "symbol": "Rp"},
    "IE": {"name": "爱尔兰", "currency": "EUR", "symbol": "€"},
    "IL": {"name": "以色列", "currency": "ILS", "symbol": "₪"},
    "IN": {"name": "印度", "currency": "INR", "symbol": "₹"},
    "IS": {"name": "冰岛", "currency": "ISK", "symbol": "kr"},
    "IT": {"name": "意大利", "currency": "EUR", "symbol": "€"},
    "JM": {"name": "牙买加", "currency": "JMD", "symbol": "J$"},
    "JO": {"name": "约旦", "currency": "JOD", "symbol": "د.ا"},
    "JP": {"name": "日本", "currency": "JPY", "symbol": "¥"},
    "KE": {"name": "肯尼亚", "currency": "KES", "symbol": "KSh"},
    "KG": {"name": "吉尔吉斯斯坦", "currency": "KGS", "symbol": "сом"},
    "KH": {"name": "柬埔寨", "currency": "KHR", "symbol": "៛"},
    "KN": {"name": "圣基茨和尼维斯", "currency": "XCD", "symbol": "$"},
    "KR": {"name": "韩国", "currency": "KRW", "symbol": "₩"},
    "KW": {"name": "科威特", "currency": "KWD", "symbol": "د.ك"},
    "KY": {"name": "开曼群岛", "currency": "KYD", "symbol": "$"},
    "KZ": {"name": "哈萨克斯坦", "currency": "KZT", "symbol": "₸"},
    "LA": {"name": "老挝", "currency": "LAK", "symbol": "₭"},
    "LB": {"name": "黎巴嫩", "currency": "LBP", "symbol": "ل.ل"},
    "LC": {"name": "圣卢西亚", "currency": "XCD", "symbol": "$"},
    "LI": {"name": "列支敦士登", "currency": "CHF", "symbol": "CHF"},
    "LK": {"name": "斯里兰卡", "currency": "LKR", "symbol": "Rs"},
    "LT": {"name": "立陶宛", "currency": "EUR", "symbol": "€"},
    "LU": {"name": "卢森堡", "currency": "EUR", "symbol": "€"},
    "LV": {"name": "拉脱维亚", "currency": "EUR", "symbol": "€"},
    "MA": {"name": "摩洛哥", "currency": "MAD", "symbol": "د.م."},
    "MD": {"name": "摩尔多瓦", "currency": "MDL", "symbol": "L"},
    "MG": {"name": "马达加斯加", "currency": "MGA", "symbol": "Ar"},
    "MK": {"name": "北马其顿", "currency": "MKD", "symbol": "ден"},
    "ML": {"name": "马里", "currency": "XOF", "symbol": "CFA"},
    "MM": {"name": "缅甸", "currency": "MMK", "symbol": "Ks"},
    "MN": {"name": "蒙古", "currency": "MNT", "symbol": "₮"},
    "MO": {"name": "澳门", "currency": "MOP", "symbol": "MOP$"},
    "MS": {"name": "蒙特塞拉特", "currency": "XCD", "symbol": "$"},
    "MT": {"name": "马耳他", "currency": "EUR", "symbol": "€"},
    "MU": {"name": "毛里求斯", "currency": "MUR", "symbol": "₨"},
    "MW": {"name": "马拉维", "currency": "MWK", "symbol": "MK"},
    "MX": {"name": "墨西哥", "currency": "MXN", "symbol": "$"},
    "MY": {"name": "马来西亚", "currency": "MYR", "symbol": "RM"},
    "MZ": {"name": "莫桑比克", "currency": "MZN", "symbol": "MT"},
    "NA": {"name": "纳米比亚", "currency": "NAD", "symbol": "$"},
    "NE": {"name": "尼日尔", "currency": "XOF", "symbol": "CFA"},
    "NG": {"name": "尼日利亚", "currency": "NGN", "symbol": "₦"},
    "NI": {"name": "尼加拉瓜", "currency": "NIO", "symbol": "C$"},
    "NL": {"name": "荷兰", "currency": "EUR", "symbol": "€"},
    "NO": {"name": "挪威", "currency": "NOK", "symbol": "kr"},
    "NP": {"name": "尼泊尔", "currency": "NPR", "symbol": "₨"},
    "NZ": {"name": "新西兰", "currency": "NZD", "symbol": "NZ$"},
    "OM": {"name": "阿曼", "currency": "OMR", "symbol": "ر.ع."},
    "PA": {"name": "巴拿马", "currency": "USD", "symbol": "$"},
    "PE": {"name": "秘鲁", "currency": "PEN", "symbol": "S/"},
    "PG": {"name": "巴布亚新几内亚", "currency": "PGK", "symbol": "K"},
    "PH": {"name": "菲律宾", "currency": "PHP", "symbol": "₱"},
    "PK": {"name": "巴基斯坦", "currency": "PKR", "symbol": "₨"},
    "PL": {"name": "波兰", "currency": "PLN", "symbol": "zł"},
    "PT": {"name": "葡萄牙", "currency": "EUR", "symbol": "€"},
    "PY": {"name": "巴拉圭", "currency": "PYG", "symbol": "₲"},
    "QA": {"name": "卡塔尔", "currency": "QAR", "symbol": "ر.ق"},
    "RO": {"name": "罗马尼亚", "currency": "RON", "symbol": "lei"},
    "RS": {"name": "塞尔维亚", "currency": "RSD", "symbol": "дин"},
    "RU": {"name": "俄罗斯", "currency": "RUB", "symbol": "₽"},
    "RW": {"name": "卢旺达", "currency": "RWF", "symbol": "FRw"},
    "SA": {"name": "沙特阿拉伯", "currency": "SAR", "symbol": "ر.س"},
    "SB": {"name": "所罗门群岛", "currency": "SBD", "symbol": "$"},
    "SC": {"name": "塞舌尔", "currency": "SCR", "symbol": "₨"},
    "SE": {"name": "瑞典", "currency": "SEK", "symbol": "kr"},
    "SG": {"name": "新加坡", "currency": "SGD", "symbol": "S$"},
    "SI": {"name": "斯洛文尼亚", "currency": "EUR", "symbol": "€"},
    "SK": {"name": "斯洛伐克", "currency": "EUR", "symbol": "€"},
    "SL": {"name": "塞拉利昂", "currency": "SLL", "symbol": "Le"},
    "SN": {"name": "塞内加尔", "currency": "XOF", "symbol": "CFA"},
    "SR": {"name": "苏里南", "currency": "SRD", "symbol": "$"},
    "ST": {"name": "圣多美和普林西比", "currency": "STN", "symbol": "Db"},
    "SV": {"name": "萨尔瓦多", "currency": "USD", "symbol": "$"},
    "SZ": {"name": "斯威士兰", "currency": "SZL", "symbol": "E"},
    "TC": {"name": "特克斯和凯科斯群岛", "currency": "USD", "symbol": "$"},
    "TD": {"name": "乍得", "currency": "XAF", "symbol": "FCFA"},
    "TH": {"name": "泰国", "currency": "THB", "symbol": "฿"},
    "TJ": {"name": "塔吉克斯坦", "currency": "TJS", "symbol": "ЅМ"},
    "TM": {"name": "土库曼斯坦", "currency": "TMT", "symbol": "m"},
    "TN": {"name": "突尼斯", "currency": "TND", "symbol": "د.ت"},
    "TO": {"name": "汤加", "currency": "TOP", "symbol": "T$"},
    "TR": {"name": "土耳其", "currency": "TRY", "symbol": "₺"},
    "TT": {"name": "特立尼达和多巴哥", "currency": "TTD", "symbol": "$"},
    "TW": {"name": "台湾", "currency": "TWD", "symbol": "NT$"},
    "TZ": {"name": "坦桑尼亚", "currency": "TZS", "symbol": "TSh"},
    "UA": {"name": "乌克兰", "currency": "UAH", "symbol": "₴"},
    "UG": {"name": "乌干达", "currency": "UGX", "symbol": "USh"},
    "US": {"name": "美国", "currency": "USD", "symbol": "$"},
    "UY": {"name": "乌拉圭", "currency": "UYU", "symbol": "$"},
    "UZ": {"name": "乌兹别克斯坦", "currency": "UZS", "symbol": "сўм"},
    "VC": {"name": "圣文森特和格林纳丁斯", "currency": "XCD", "symbol": "$"},
    "VE": {"name": "委内瑞拉", "currency": "VES", "symbol": "Bs."},
    "VG": {"name": "英属维尔京群岛", "currency": "USD", "symbol": "$"},
    "VN": {"name": "越南", "currency": "VND", "symbol": "₫"},
    "WS": {"name": "萨摩亚", "currency": "WST", "symbol": "T"},
    "YE": {"name": "也门", "currency": "YER", "symbol": "﷼"},
    "ZA": {"name": "南非", "currency": "ZAR", "symbol": "R"},
    "ZM": {"name": "赞比亚", "currency": "ZMW", "symbol": "ZK"}
}

# Create a mapping from Chinese names to country codes for easy lookup
COUNTRY_NAME_TO_CODE = {info["name"]: code for code, info in SUPPORTED_COUNTRIES.items()}

# Create a set of all valid country inputs (codes and names)
VALID_COUNTRY_INPUTS = set(COUNTRY_NAME_TO_CODE.keys()) | set(SUPPORTED_COUNTRIES.keys())

# Standard Unicode flag emojis
# Source: https://emojipedia.org/flags
UNICODE_FLAG_EMOJIS = {
    "AE": "🇦🇪", "AG": "🇦🇬", "AI": "🇦🇮", "AL": "🇦🇱", "AM": "🇦🇲", "AO": "🇦🇴",
    "AR": "🇦🇷", "AT": "🇦🇹", "AU": "🇦🇺", "AZ": "🇦🇿", "BB": "🇧🇧", "BE": "🇧🇪",
    "BF": "🇧🇫", "BG": "🇧🇬", "BH": "🇧🇭", "BJ": "🇧🇯", "BM": "🇧🇲", "BN": "🇧🇳",
    "BO": "🇧🇴", "BR": "🇧🇷", "BS": "🇧🇸", "BW": "🇧🇼", "BY": "🇧🇾", "BZ": "🇧🇿",
    "CA": "🇨🇦", "CH": "🇨🇭", "CL": "🇨🇱", "CN": "🇨🇳", "CO": "🇨🇴", "CR": "🇨🇷",
    "CV": "🇨🇻", "CY": "🇨🇾", "CZ": "🇨🇿", "DE": "🇩🇪", "DK": "🇩🇰", "DM": "🇩🇲",
    "DO": "🇩🇴", "DZ": "🇩🇿", "EC": "🇪🇨", "EE": "🇪🇪", "EG": "🇪🇬", "ES": "🇪🇸",
    "FI": "🇫🇮", "FJ": "🇫🇯", "FM": "🇫🇲", "FR": "🇫🇷", "GB": "🇬🇧", "GD": "🇬🇩",
    "GH": "🇬🇭", "GM": "🇬🇲", "GR": "🇬🇷", "GT": "🇬🇹", "GW": "🇬🇼", "GY": "🇬🇾",
    "HK": "🇭🇰", "HN": "🇭🇳", "HR": "🇭🇷", "HU": "🇭🇺", "ID": "🇮🇩", "IE": "🇮🇪",
    "IL": "🇮🇱", "IN": "🇮🇳", "IO": "🇮🇴", "IQ": "🇮🇶", "IR": "🇮🇷", "IS": "🇮🇸",
    "IT": "🇮🇹", "JM": "🇯🇲", "JO": "🇯🇴", "JP": "🇯🇵", "KE": "🇰🇪", "KG": "🇰🇬",
    "KH": "🇰🇭", "KN": "🇰🇳", "KR": "🇰🇷", "KW": "🇰🇼", "KY": "🇰🇾", "KZ": "🇰🇿",
    "LA": "🇱🇦", "LB": "🇱🇧", "LC": "🇱🇨", "LI": "🇱🇮", "LK": "🇱🇰", "LT": "🇱🇹",
    "LU": "🇱🇺", "LV": "🇱🇻", "MA": "🇲🇦", "MD": "🇲🇩", "MG": "🇲🇬", "MK": "🇲🇰",
    "ML": "🇲🇱", "MM": "🇲🇲", "MN": "🇲🇳", "MO": "🇲🇴", "MS": "🇲🇸", "MT": "🇲🇹",
    "MU": "🇲🇺", "MW": "🇲🇼", "MX": "🇲🇽", "MY": "🇲🇾", "MZ": "🇲🇿", "NA": "🇳🇦",
    "NE": "🇳🇪", "NG": "🇳🇬", "NI": "🇳🇮", "NL": "🇳🇱", "NO": "🇳🇴", "NP": "🇳🇵",
    "NZ": "🇳🇿", "OM": "🇴🇲", "PA": "🇵🇦", "PE": "🇵🇪", "PG": "🇵🇬", "PH": "🇵🇭",
    "PK": "🇵🇰", "PL": "🇵🇱", "PT": "🇵🇹", "PY": "🇵🇾", "QA": "🇶🇦", "RO": "🇷🇴",
    "RS": "🇷🇸", "RU": "🇷🇺", "RW": "🇷🇼", "SA": "🇸🇦", "SB": "🇸🇧", "SC": "🇸🇨",
    "SD": "🇸🇩", "SE": "🇸🇪", "SG": "🇸🇬", "SI": "🇸🇮", "SK": "🇸🇰", "SL": "🇸🇱",
    "SN": "🇸🇳", "SO": "🇸🇴", "SR": "🇸🇷", "SS": "🇸🇸", "ST": "🇸🇹", "SV": "🇸🇻",
    "SY": "🇸🇾", "SZ": "🇸🇿", "TC": "🇹🇨", "TD": "🇹🇩", "TH": "🇹🇭", "TJ": "🇹🇯",
    "TM": "🇹🇲", "TN": "🇹🇳", "TO": "🇹🇴", "TR": "🇹🇷", "TT": "🇹🇹", "TV": "🇹🇻",
    "TW": "🇹🇼", "TZ": "🇹🇿", "UA": "🇺🇦", "UG": "🇺🇬", "US": "🇺🇸", "UY": "🇺🇾",
    "UZ": "🇺🇿", "VC": "🇻🇨", "VE": "🇻🇪", "VG": "🇻🇬", "VN": "🇻🇳", "WS": "🇼🇸",
    "YE": "🇾🇪", "ZA": "🇿🇦", "ZM": "🇿🇲", "ZW": "🇿🇼"
}

def get_country_flag(country_code: str) -> str:
    """Returns the standard Unicode flag emoji for a given country code."""
    return UNICODE_FLAG_EMOJIS.get(country_code.upper(), "🏳️")